# Generated by Django 3.2.7 on 2021-10-08 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('quantificador', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preparo', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('ingrediente_receita', models.ManyToManyField(to='receitas.Ingrediente')),
                ('tags', models.ManyToManyField(to='receitas.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='produto_ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receitas.produto'),
        ),
    ]
