# Generated by Django 3.2.7 on 2021-10-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='quantificador',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
