# Generated by Django 3.2.7 on 2021-10-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_alter_ingrediente_quantificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='quantificador',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
